### ISSUE TITLE
[Bug] 1초 마다 자동 fetching시 메인 페이지 전체 리렌더링 

### ISSUE THREAD

**Issue by loco9939** [TAMAS-Inc/tama#129]
## 🐛 현재 상황

- 1초 마다 Auto Data Fetching => 메인 페이지 리렌더링

## 📃 세부 사항

- 아마도 1초마다 fetchTime 상태를 변경하기 때문에 리렌더링이 발생하는 것 같다.
- 15초 마다 자동 페칭되도록했는데, 가끔 15초되기 전에 자기 혼자 렌더링되는 경우가 있다.
로딩시간이 길어질 경우, 이후에 로딩되었을 때를 기준으로 15초를 다시 세는 것 처럼 보인다.
- 이 경우 종속성을 params만 설정해주면 15초마다 params 데이터를 변경할 때마다 렌더링이 된다.

## ✏️ 할 일
- [x] useEffect 종속성 배열 수정하기
- [x] 15초 마다 텍스트 감소하는 상태 sync버튼 내부로 이동
- [x] sync 버튼 클릭 시 시간 상태 초기화 하기
- [x] 15초 마다 Fetching되는 spinner 모션 추가
- [x] 분석 페이지에서 사용하는 sync 버튼 구분하기

**Comment by loco9939** [comment]
15초 마다 자동 페칭되도록했는데, 가끔 15초되기 전에 자기 혼자 렌더링되는 경우가 있다.
로딩시간이 길어질 경우, 이후에 로딩되었을 때를 기준으로 15초를 다시 세는 것 처럼 보인다.

이 경우 종속성을 15초가 지났을 때만 fetching 하도록 바꿔보자.

**Comment by codeisneverodd** [comment]
Sync 버튼 컴포넌트에게 Memo 걸어야할 것 같아요~
