### ISSUE TITLE
[Feature] inquiry 페이지 모달 및 서버 요청 기능 개발

### ISSUE THREAD

**Issue by loco9939** [TAMAS-Inc/tama#52]
## ✨ 추가할 기능

- 문의하기 작성완료 버튼 클릭 -> 모달 메시지 띄우기
- 모달 메시지 확인 클릭 -> 해당 데이터를 서버에 post 요청 
```ts
// 서버에 post 요청 보낼 데이터
interface Inquiry {
  inquiryId: string;
  email: string;
  title: string;
  content: string;
}
```

## 📃 세부 사항

- 서버에 post 요청 보내기 : 미정

## ✏️ 할 일
- [x] 문의하기 작성완료 버튼 클릭 => 모달 상태 관리
- [x] 모달 확인 버튼 클릭 => 이전페이지 이동
- [x] dim 클릭시 아무일도 발생 하지 않는다.

**Comment by codeisneverodd** [comment]
모달 메시지에 쓰일 모달은 우선 기존 Message 모달로 사용하고, 이후 BaseModal로 리팩토링하면 좋을 것 같아요~

**Comment by codeisneverodd** [comment]
서버 Post URL은 12/16에 제공해드리겠습니다 👍
