### ISSUE TITLE
[Feature] 유저 데이터 저장 및 출근 정보 수정 기능

### ISSUE THREAD

**Issue by jiseung-kang** [TAMAS-Inc/tama#54]
## ✨ 추가할 기능

- 유저 정보 저장
  - 약관 동의 정보
  - 출근 정보 저장

## 📃 세부 사항

- 어플 실행 첫 페이지 변경 : landing ➡️ landing/agreement
  - 기존 랜딩 페이지는 앱 구현 시 적용할 것
- useCommutes hooks 개발
  - 출근지 추가기능
```ts
type useCommutes = () => { createCommute }
```

## ✏️ 할 일
- [x] 유저 정보가 없으면 landing/agreement으로 리디렉션
- [x] 약관 동의 정보 저장
- [x] Commute 페이지 컴포넌트 재사용을 위한 로직 분리 및 출근 정보 수정 페이지 개발

**Comment by loco9939** [comment]
유저 출근 정보는 recoil-persist 라이브러리를 사용하여 로컬에 저장되도록 구현해놨습니다.
